### ISSUE TITLE
State

### ISSUE THREAD

**Issue by AdrianMW** [ahmetkgunay/LinkedinIOSHelper#1]
Hey,

Thanks for sharing this great library, I really like that there are no dependencies

I do have a concern however that the state is set statically in the code:

```
self.service = [LinkedInServiceManager serviceForPresentingViewController:_sender
                                                             cancelButtonText:self.cancelButtonText
                                                             appSettings:[LinkedInAppSettings settingsWithClientSecret:_clientSecret
                                                             clientId:_clientId
                                                             redirectUrl:_applicationWithRedirectURL
                                                             permissions:_permissions
                                                             state:@"DCEEFWF45453sdffef424"]];
```

Which means the state value is very easy to guess, opening it up to a possible CSFR attack.
https://developer.linkedin.com/docs/oauth2

Is there a way to set this in the client? 

 If not do would you be able to do a update so this can be set in the client through the requestMeWithSenderViewController: request or on the LinkedInHelper Object

Cheers

**Comment by ahmetgunay** [comment]
Hey thanks for your support and your meaningfull code review i will have
update after 2 hours for you which client can set state.

17 Ağustos 2015 Pazartesi tarihinde, AdrianMW <notifications@github.com>
yazdı:

> Hey,
>
> Thanks for sharing this great library, I really like that there are no
> dependencies
>
> I do have a concern however that the state is set statically in the code:
>
> self.service = [LinkedInServiceManager serviceForPresentingViewController:_sender
>                                                              cancelButtonText:self.cancelButtonText
>                                                              appSettings:[LinkedInAppSettings settingsWithClientSecret:_clientSecret
>                                                              clientId:_clientId
>                                                              redirectUrl:_applicationWithRedirectURL
>                                                              permissions:_permissions
>                                                              state:@"DCEEFWF45453sdffef424"]];
>
> Which means the state value is very easy to guess, opening it up to a
> possible CSFR attack.
> https://developer.linkedin.com/docs/oauth2
>
> Is there a way to set this in the client?
>
> If not do would you be able to do a update so this can be set in the
> client through the requestMeWithSenderViewController: request or on the
> LinkedInHelper Object
>
> Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ahmetkgunay/LinkedinIOSHelper/issues/1>.
>


-- 
Iyi calismalar

Ahmet Kazim Günay
iOS Developer Mobven

**Comment by ahmetkgunay** [comment]
Hey @AdrianMW I updated my library and after now u can set any state u want.

Thanks for your special thoughts and code review..

**Comment by AdrianMW** [comment]
Thanks for the very speedy update :+1:
