### ISSUE TITLE
OAuth v.2

### ISSUE THREAD

**Issue by anu-2810** [ahmetkgunay/LinkedinIOSHelper#11]
Does this framework support OAuth V.2.?

**Comment by ahmetkgunay** [comment]
This Library directly connects to the https://www.linkedin.com/uas/oauth2/authorization to get auth code from linkedin

**Comment by anu-2810** [comment]
But Linkedin recently announced the api updation. 
"https://www.linkedin.com/oauth/v2/authorization" to get auth. Does this api "https://www.linkedin.com/uas/oauth2/authorization" acceptable after march 1st?

**Comment by ahmetkgunay** [comment]
Please reopen issue if it is not working afte 1 March but i guess it will be working..
