### ISSUE TITLE
Logging out

### ISSUE THREAD

**Issue by AdrianMW** [ahmetkgunay/LinkedinIOSHelper#2]
Hey,

I am having trouble finding a way to clear the access keys out of the memory and log the user out

In schools they are often on shared devices and users need to login and out frequently.

Cheers

**Comment by ahmetkgunay** [comment]
You need to clear accessToken data and authorizationCode ?

**Comment by AdrianMW** [comment]
yes, so it is back to the same state as when the user first opened the app

**Comment by ahmetkgunay** [comment]
U can delete all tokens like below: 

```
LinkedInHelper *linkedIn = [LinkedInHelper sharedInstance];
[linkedIn logout];
```

**Comment by AdrianMW** [comment]
Thanks
