### ISSUE TITLE
Storing the Token data securley

### ISSUE THREAD

**Issue by AdrianMW** [ahmetkgunay/LinkedinIOSHelper#4]
Hey,

This is the last and probably most important issue security-wise.

Could the LINKEDIN_TOKEN_KEY be stored in the secure keychain rather than the less secure NSUserDefaults?

Cheers

**Comment by ahmetkgunay** [comment]
I will have update today to store in keychain. And will solve all the other issues. Thanks for your feedback.

**Comment by AdrianMW** [comment]
wow, I look forward to it :+1:

**Comment by ahmetkgunay** [comment]
Updated!. Tokens are stored in secure keychain right now.

**Comment by AdrianMW** [comment]
Great, I will give this a whirl
