### ISSUE TITLE
Login Failure error

### ISSUE THREAD

**Issue by NareshKalakuntla** [ahmetkgunay/LinkedinIOSHelper#5]
Hi,
The redirection url after successful authorization of LinkedIn user consists of fragment identifier "#".
For eg I have logged in to Li and the final re-direction url is of form 

> https://www.google.com/?code=xxx&state=xxx#!

The SDK is failing to check the state in the service manager and the state in the url.
Received state in service manager in **"xxx"** but from url is **"xxx#!"** and fails while verifying it.
We must not consider the fragment identifier in the parameters. This is causing the error in login in SDK even if the user is logged in successfully in the webview.

**Comment by ahmetkgunay** [comment]
fixed it thanks to you.

**Comment by ahmetkgunay** [comment]
Hi,

Thank you for your answer!  I was on my military service thats why i
couldnt connect the internet meanwhile.

I am done with my military service so i am free now and updated my pod
thank you.

2016-07-10 20:26 GMT+03:00 Naresh Kalakuntla notifications@github.com:
