### ISSUE TITLE
LinkedInAuthorizationViewController customization

### ISSUE THREAD

**Issue by NickChayka** [ahmetkgunay/LinkedinIOSHelper#8]
Hi!

It is possible to add some methods for customization of the WebView, NavigationBar, NavigationBarItem in the LinkedInAuthorizationViewController class?

Thanks!

**Comment by ahmetkgunay** [comment]
Hi, right now it is not possible for customization LinkedInAuthorizationViewController. You can just set the Close button's text. But i can add it in a day.

**Comment by ahmetkgunay** [comment]
I added appearance support for linkinedIn auth viewcontroller's nav bar
