### ISSUE TITLE
How can we set permision in Swift

### ISSUE THREAD

**Issue by RahulBangde07** [ahmetkgunay/LinkedinIOSHelper#9]
not able to set permission in Swift

**Comment by ahmetkgunay** [comment]
Did you checked SwiftDemo? 
You can set permissions by settings permissions array like: 

let permissions : [Int] = [Permissions.BasicProfile.rawValue, Permissions.EmailAddress.rawValue, Permissions.Share.rawValue, Permissions.CompanyAdmin.rawValue]
